/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-10-13 15:32:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class updatevent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Update Event Page</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/home.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f4f7f6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container {\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-heading {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group label {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-submit {\r\n");
      out.write("	background-color: #198754;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-cancel {\r\n");
      out.write("	background-color: #6c757d;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username-link {\r\n");
      out.write("	color: #0d0d0e; /* Color of the username */\r\n");
      out.write("	text-decoration: none; /* Remove underline */\r\n");
      out.write("	font-weight: bold; /* Make it bold */\r\n");
      out.write("	margin-right: 50px;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username-link1 {\r\n");
      out.write("	color: #0d0d0e; /* Color of the username */\r\n");
      out.write("	text-decoration: none; /* Remove underline */\r\n");
      out.write("	font-weight: bold; /* Make it bold */\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username-link:hover {\r\n");
      out.write("	color: rgb(14, 85, 85);\r\n");
      out.write("	text-decoration: none; /* No underline on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".username-link1:hover {\r\n");
      out.write("	color: rgb(14, 85, 85);\r\n");
      out.write("	text-decoration: none; /* No underline on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Announcement Section */\r\n");
      out.write(".announcement-section {\r\n");
      out.write("	background: radial-gradient(circle at top left, #91ddd2, #bec4c5);\r\n");
      out.write("	/* Radial gradient */\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	font-size: 36px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table th {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table tbody th {\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add User and Search Bar Section */\r\n");
      out.write(".search-bar-section {\r\n");
      out.write("	margin: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar-section form {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-bar-section .btn {\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-user-btn {\r\n");
      out.write("	background-color: #0d6efd;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".find-user-btn {\r\n");
      out.write("	background-color: #198754;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"row align-items-center\">\r\n");
      out.write("			<!-- Logo Section -->\r\n");
      out.write("			<div class=\"col-md-6\">\r\n");
      out.write("				<img src=\"image/logo1.jpg\" alt=\"Reuban College Logo\"\r\n");
      out.write("					class=\"img-fluid\" style=\"width: 70%; height: 30%;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- User Profile Section -->\r\n");
      out.write("			<div class=\"col-md-6 text-end\">\r\n");
      out.write("				<div class=\"d-flex align-items-center justify-content-end\">\r\n");
      out.write("					<a href=\"/profile\" class=\"username-link\">Username</a> <a href=\"\"\r\n");
      out.write("						class=\"username-link1\"><i class=\"bi bi-person-circle\"\r\n");
      out.write("						style=\"font-size: 50px; margin-right: 10px;\"></i></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Header Section -->\r\n");
      out.write("	<header class=\"d-flex justify-content-end align-items-center\"\r\n");
      out.write("		style=\"background-color: #839492; color: #fff; padding: 10px;\">\r\n");
      out.write("		<nav>\r\n");
      out.write("			<ul class=\"nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"btn custom-btn me-4\"\r\n");
      out.write("					href=\"adminHome.jsp\">Home</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"btn custom-btn me-4\"\r\n");
      out.write("					href=\"managepri.jsp\">Manage Events</a></li>\r\n");
      out.write("				<!-- <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"btn custom-btn me-4\" href=\"\">Make An Announcement</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"btn custom-btn me-4\" href=\"\">Check Attendance</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"btn custom-btn me-4\" href=\"\">Communication</a>\r\n");
      out.write("                </li> -->\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"btn custom-btn me-4\" href=\"\">Log	out</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-8 form-container\">\r\n");
      out.write("				<h2 class=\"form-heading\">Update Event</h2>\r\n");
      out.write("\r\n");
      out.write("				<!-- Form for adding user -->\r\n");
      out.write("				<form action=\"updatevent\" method=\"post\">\r\n");
      out.write("					<div class=\"mb-3 form-group\">\r\n");
      out.write("                        <label for=\"name\">eventid</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"is\" name=\"id\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ptss.eventid}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' / readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3 form-group\">\r\n");
      out.write("                        <label for=\"name\">eventName</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ptss.eventName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3 form-group\">\r\n");
      out.write("                        <label for=\"InCharge\">eventInCharge</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"InCharge\" name=\"InCharge\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ptss.eventInCharge}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-3 form-group\">\r\n");
      out.write("                        <label for=\"userType\">eventDate</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"Date\" name=\"Date\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ptss.eventDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("					<!-- Buttons -->\r\n");
      out.write("					<div class=\"form-group mb-2 row\">\r\n");
      out.write("						<input type=\"submit\" class=\"btn btn-warning\" value=\"Update Event\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<!-- Footer Section -->\r\n");
      out.write("	<footer class>\r\n");
      out.write("		<p>\r\n");
      out.write("			&copy; 2024 Reuban College G10. <br>All rights reserved.\r\n");
      out.write("		</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
